---
- hosts: all
  become: yes
  tasks:
  - name: des install git on all my nodes
    apt:
      name: git
      state: absent 
  - name:  des install wbserver on ubutnu (apache2)
    apt:
      name: apache2
      state: present
  