---
- hosts: webservers
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver on redhat 
    yum:
      name: httpd
      state: present

  - name: start the httpd service
    service:
      name: httpd
      state: started

  - name: copy file(index.html) into all nodes
    template:
      src: myindex.j2
      dest: /var/www/html/index.html

  - name: restart the httpd service
    service:
      name: httpd
      start: restarted
      